name: Deploy Storybook

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # baixa a versão atualizada do código

      - name: Setup Node.js
        uses: actions/setup-node@v3 # instala o node no ambiente
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci --legacy-peer-deps # instala dependências de produção sem entradas extras

      - name: Build Storybook
        run: npm run build-storybook # roda a build presente em package.json

      - name: Deploy Storybook
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static # roda o deploy presente em package.json
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} # vars setadas automaticamente/ cria branchs e acessos para o github pages

        # deploy irá olhar sempre para o storybook-static
        # --ci indica que não terá entradas externas nem confirmações